# Generated by Django 3.0.3 on 2020-03-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'プロファイル', 'verbose_name_plural': 'プロファイル'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
