# Generated by Django 3.0.3 on 2020-03-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200304_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', '女性'), ('male', '男性'), ('not_applicable', '秘密')], max_length=20),
        ),
    ]
