# Generated by Django 3.0.3 on 2020-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200304_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm_department',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
    ]
