# Generated by Django 3.0.3 on 2020-03-11 21:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200304_0733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tm_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='表示順')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('service_name', models.CharField(max_length=200, verbose_name='サービス名')),
                ('upload_file', models.FileField(null=True, upload_to='upload', verbose_name='アップロードファイル')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Tm_Department', verbose_name='部門')),
            ],
            options={
                'verbose_name': 'サービスマスタ',
                'verbose_name_plural': 'サービスマスタ',
                'db_table': 'Tm_Service',
            },
        ),
        migrations.CreateModel(
            name='Tm_Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='表示順')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('workflow_route', models.IntegerField(choices=[(1, '通常'), (2, '特別')], default='1', verbose_name='承認経路')),
                ('workflow_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='承認回数')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Tm_Department', verbose_name='部門')),
            ],
            options={
                'verbose_name': '承認マスタ',
                'verbose_name_plural': '承認マスタ',
                'db_table': 'Tm_Workflow',
            },
        ),
        migrations.CreateModel(
            name='Tm_Workflow_Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='表示順')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('amount_min', models.IntegerField(null=True, verbose_name='金額（下限）')),
                ('amount_max', models.IntegerField(null=True, verbose_name='金額（下限）')),
                ('rate_min', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='利益率（下限）')),
                ('rate_max', models.DecimalField(decimal_places=1, max_digits=4, null=True, verbose_name='利益率（下限）')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excelapp.Tm_Service', verbose_name='サービス')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excelapp.Tm_Workflow', verbose_name='承認')),
            ],
            options={
                'verbose_name': '承認経路条件マスタ',
                'verbose_name_plural': '承認経路条件マスタ',
                'db_table': 'Tm_Workflow_Conditions',
            },
        ),
        migrations.CreateModel(
            name='Tm_Authorizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, verbose_name='表示順')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('workflow_count', models.IntegerField(default=1, verbose_name='承認回数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='承認者')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='excelapp.Tm_Workflow', verbose_name='承認')),
            ],
            options={
                'verbose_name': '承認者マスタ',
                'verbose_name_plural': '承認者マスタ',
                'db_table': 'Tm_Authorizer',
            },
        ),
    ]
