# Generated by Django 3.0.3 on 2020-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm_authorizer',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='tm_service',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='tm_service',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='upload', verbose_name='アップロードファイル'),
        ),
        migrations.AlterField(
            model_name='tm_workflow',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='tm_workflow_conditions',
            name='amount_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額（上限）'),
        ),
        migrations.AlterField(
            model_name='tm_workflow_conditions',
            name='amount_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='金額（下限）'),
        ),
        migrations.AlterField(
            model_name='tm_workflow_conditions',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='tm_workflow_conditions',
            name='rate_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='利益率（上限）'),
        ),
        migrations.AlterField(
            model_name='tm_workflow_conditions',
            name='rate_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='利益率（下限）'),
        ),
    ]
